[tool.poetry]
name = "nixopsenv"
version = "2.0.0"
description = "NixOps 2.0"
authors = ["Adam Hoese <adam.hose@tweag.io>"]

[tool.poetry.dependencies]
python = "^3.9"
nixops = {git = "https://github.com/NixOS/nixops.git"}
nixops-aws = {git = "https://github.com/rehno-lindeque/nixops-aws.git", branch = "wip-ec2-target"}
typing-extensions = "^3.10.0.2"

[tool.poetry.dev-dependencies]
sphinx = "^3.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
